AWSTemplateFormatVersion: '2010-09-09'
Description: Template final - Cria uma instância EC2 Free Tier com grupo de segurança na região Ohio

Resources:
  MeuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group basico para EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-051f8a213df8bc089
      KeyName: minha-chave-pessoal
      SecurityGroups:
        - !Ref MeuSecurityGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y httpd
          sudo systemctl start httpd
          sudo systemctl enable httpd
          echo "
          Servidor Web Ativo! 🚀
          " > /var/www/html/index.html
